---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  namespace: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      initContainers:
        - name: chown-nexusdata-owner-to-nexus
          image: busybox:1.34.1
          command: [ "/bin/sh","-c" ]
          args: [ "chown -R 13:13 /var/spool/squid" ]
          volumeMounts:
            - name: squid-data
              mountPath: /var/spool/squid
      containers:
        - name: squid
          image: ubuntu/squid:4.10-20.04_beta
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3128
              name: squid
              protocol: TCP
          volumeMounts:
            - name: squid-config-volume
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            - name: squid-data
              mountPath: /var/spool/squid
      volumes:
        - name: squid-config-volume
          configMap:
            name: squid-config
            items:
              - key: squid
                path: squid.conf
        - name: squid-data
          persistentVolumeClaim:
            claimName: pvc-squid
---
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: dev-tools
  labels:
    app: squid
spec:
  ports:
    - name: http
      protocol: TCP
      port: 13128
      targetPort: 3128
  selector:
    app: squid
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-squid
  namespace: dev-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage