apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-common-pvc
  namespace: dev-tools
spec:
  storageClassName: oci-bv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi