server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=quotes_data
    username: postgres
    password: pass
  liquibase:
    change-log: classpath:db/changelog/databaseChangeLog.yml
    liquibase-schema: public
    contexts: "!local-test"

market:
  data:
    tcs:
      url: 'http://mock'
      token: "testToken"