/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tech.ineb.lib.common.entities.quotes.data.History;
import tech.ineb.lib.common.entities.quotes.data.Keys;
import tech.ineb.lib.common.entities.quotes.data.tables.records.StocksRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stocks extends TableImpl<StocksRecord> {

    private static final long serialVersionUID = 339335895;

    /**
     * The reference instance of <code>history.stocks</code>
     */
    public static final Stocks STOCKS = new Stocks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StocksRecord> getRecordType() {
        return StocksRecord.class;
    }

    /**
     * The column <code>history.stocks.id</code>.
     */
    public final TableField<StocksRecord, UUID> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>history.stocks.code</code>.
     */
    public final TableField<StocksRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>history.stocks.name</code>.
     */
    public final TableField<StocksRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>history.stocks.version</code>.
     */
    public final TableField<StocksRecord, Integer> VERSION = createField(DSL.name("version"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>history.stocks</code> table reference
     */
    public Stocks() {
        this(DSL.name("stocks"), null);
    }

    /**
     * Create an aliased <code>history.stocks</code> table reference
     */
    public Stocks(String alias) {
        this(DSL.name(alias), STOCKS);
    }

    /**
     * Create an aliased <code>history.stocks</code> table reference
     */
    public Stocks(Name alias) {
        this(alias, STOCKS);
    }

    private Stocks(Name alias, Table<StocksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Stocks(Name alias, Table<StocksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Stocks(Table<O> child, ForeignKey<O, StocksRecord> key) {
        super(child, key, STOCKS);
    }

    @Override
    public Schema getSchema() {
        return History.HISTORY;
    }

    @Override
    public UniqueKey<StocksRecord> getPrimaryKey() {
        return Keys.STOCKS_PKEY;
    }

    @Override
    public List<UniqueKey<StocksRecord>> getKeys() {
        return Arrays.<UniqueKey<StocksRecord>>asList(Keys.STOCKS_PKEY);
    }

    @Override
    public TableField<StocksRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public Stocks as(String alias) {
        return new Stocks(DSL.name(alias), this);
    }

    @Override
    public Stocks as(Name alias) {
        return new Stocks(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stocks rename(String name) {
        return new Stocks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stocks rename(Name name) {
        return new Stocks(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
