#Streaming: wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws

market:
  data:
    tcs:
      url: 'https://api-invest.tinkoff.ru/openapi/'
      token: "t.QLGTNE-nwHy4DW-aW6PsxYzGXOrhX3WU6Sw0VNuemIDaXn8PnjcmDN6pkdU_6YE7TW7Txmyb4LhNQEHkufYKgA"