/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import tech.ineb.lib.common.entities.quotes.data.tables.Countries;
import tech.ineb.lib.common.entities.quotes.data.tables.Currencies;
import tech.ineb.lib.common.entities.quotes.data.tables.Equities;
import tech.ineb.lib.common.entities.quotes.data.tables.Orders;
import tech.ineb.lib.common.entities.quotes.data.tables.Quotes;
import tech.ineb.lib.common.entities.quotes.data.tables.Stocks;
import tech.ineb.lib.common.entities.quotes.data.tables.Ticks;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class History extends SchemaImpl {

    private static final long serialVersionUID = 545601870;

    /**
     * The reference instance of <code>history</code>
     */
    public static final History HISTORY = new History();

    /**
     * The table <code>history.countries</code>.
     */
    public final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>history.currencies</code>.
     */
    public final Currencies CURRENCIES = Currencies.CURRENCIES;

    /**
     * The table <code>history.equities</code>.
     */
    public final Equities EQUITIES = Equities.EQUITIES;

    /**
     * The table <code>history.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>history.quotes</code>.
     */
    public final Quotes QUOTES = Quotes.QUOTES;

    /**
     * The table <code>history.stocks</code>.
     */
    public final Stocks STOCKS = Stocks.STOCKS;

    /**
     * The table <code>history.ticks</code>.
     */
    public final Ticks TICKS = Ticks.TICKS;

    /**
     * No further instances allowed
     */
    private History() {
        super("history", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Countries.COUNTRIES,
            Currencies.CURRENCIES,
            Equities.EQUITIES,
            Orders.ORDERS,
            Quotes.QUOTES,
            Stocks.STOCKS,
            Ticks.TICKS);
    }
}
