/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data;


import tech.ineb.lib.common.entities.quotes.data.tables.Countries;
import tech.ineb.lib.common.entities.quotes.data.tables.Currencies;
import tech.ineb.lib.common.entities.quotes.data.tables.Equities;
import tech.ineb.lib.common.entities.quotes.data.tables.Orders;
import tech.ineb.lib.common.entities.quotes.data.tables.Quotes;
import tech.ineb.lib.common.entities.quotes.data.tables.Stocks;
import tech.ineb.lib.common.entities.quotes.data.tables.Ticks;


/**
 * Convenience access to all tables in history
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>history.countries</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>history.currencies</code>.
     */
    public static final Currencies CURRENCIES = Currencies.CURRENCIES;

    /**
     * The table <code>history.equities</code>.
     */
    public static final Equities EQUITIES = Equities.EQUITIES;

    /**
     * The table <code>history.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>history.quotes</code>.
     */
    public static final Quotes QUOTES = Quotes.QUOTES;

    /**
     * The table <code>history.stocks</code>.
     */
    public static final Stocks STOCKS = Stocks.STOCKS;

    /**
     * The table <code>history.ticks</code>.
     */
    public static final Ticks TICKS = Ticks.TICKS;
}
