---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pvc
  namespace: dev-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: oci-bv
---