---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pvc
  namespace: dev-tools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
---