/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Countries implements Serializable {

    private static final long serialVersionUID = -169958261;

    private UUID    id;
    private Long    code;
    private String  name;
    private String  fullName;
    private String  alpha2;
    private String  alpha3;
    private Integer version;

    public Countries() {}

    public Countries(Countries value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.fullName = value.fullName;
        this.alpha2 = value.alpha2;
        this.alpha3 = value.alpha3;
        this.version = value.version;
    }

    public Countries(
        UUID    id,
        Long    code,
        String  name,
        String  fullName,
        String  alpha2,
        String  alpha3,
        Integer version
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.fullName = fullName;
        this.alpha2 = alpha2;
        this.alpha3 = alpha3;
        this.version = version;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Long getCode() {
        return this.code;
    }

    public void setCode(Long code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAlpha2() {
        return this.alpha2;
    }

    public void setAlpha2(String alpha2) {
        this.alpha2 = alpha2;
    }

    public String getAlpha3() {
        return this.alpha3;
    }

    public void setAlpha3(String alpha3) {
        this.alpha3 = alpha3;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Countries (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(fullName);
        sb.append(", ").append(alpha2);
        sb.append(", ").append(alpha3);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
