/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Currencies implements Serializable {

    private static final long serialVersionUID = -1028813968;

    private UUID    id;
    private String  code;
    private String  name;
    private Long    numericCode;
    private Integer version;

    public Currencies() {}

    public Currencies(Currencies value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.numericCode = value.numericCode;
        this.version = value.version;
    }

    public Currencies(
        UUID    id,
        String  code,
        String  name,
        Long    numericCode,
        Integer version
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.numericCode = numericCode;
        this.version = version;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getNumericCode() {
        return this.numericCode;
    }

    public void setNumericCode(Long numericCode) {
        this.numericCode = numericCode;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Currencies (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(numericCode);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
