/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements Serializable {

    private static final long serialVersionUID = 391780833;

    private UUID          id;
    private BigDecimal    volume;
    private BigDecimal    price;
    private BigDecimal    amount;
    private Integer       orderType;
    private Integer       orderStatus;
    private LocalDateTime created;
    private Integer       version;
    private UUID          equityId;

    public Orders() {}

    public Orders(Orders value) {
        this.id = value.id;
        this.volume = value.volume;
        this.price = value.price;
        this.amount = value.amount;
        this.orderType = value.orderType;
        this.orderStatus = value.orderStatus;
        this.created = value.created;
        this.version = value.version;
        this.equityId = value.equityId;
    }

    public Orders(
        UUID          id,
        BigDecimal    volume,
        BigDecimal    price,
        BigDecimal    amount,
        Integer       orderType,
        Integer       orderStatus,
        LocalDateTime created,
        Integer       version,
        UUID          equityId
    ) {
        this.id = id;
        this.volume = volume;
        this.price = price;
        this.amount = amount;
        this.orderType = orderType;
        this.orderStatus = orderStatus;
        this.created = created;
        this.version = version;
        this.equityId = equityId;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public BigDecimal getVolume() {
        return this.volume;
    }

    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Integer getOrderType() {
        return this.orderType;
    }

    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    public Integer getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    public LocalDateTime getCreated() {
        return this.created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public UUID getEquityId() {
        return this.equityId;
    }

    public void setEquityId(UUID equityId) {
        this.equityId = equityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(id);
        sb.append(", ").append(volume);
        sb.append(", ").append(price);
        sb.append(", ").append(amount);
        sb.append(", ").append(orderType);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(created);
        sb.append(", ").append(version);
        sb.append(", ").append(equityId);

        sb.append(")");
        return sb.toString();
    }
}
