/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quotes implements Serializable {

    private static final long serialVersionUID = 355014723;

    private UUID          id;
    private BigDecimal    open;
    private BigDecimal    high;
    private BigDecimal    low;
    private BigDecimal    close;
    private LocalDateTime time;
    private Integer       timeFrame;
    private UUID          equityId;
    private Integer       version;
    private UUID          equitiesid;

    public Quotes() {}

    public Quotes(Quotes value) {
        this.id = value.id;
        this.open = value.open;
        this.high = value.high;
        this.low = value.low;
        this.close = value.close;
        this.time = value.time;
        this.timeFrame = value.timeFrame;
        this.equityId = value.equityId;
        this.version = value.version;
        this.equitiesid = value.equitiesid;
    }

    public Quotes(
        UUID          id,
        BigDecimal    open,
        BigDecimal    high,
        BigDecimal    low,
        BigDecimal    close,
        LocalDateTime time,
        Integer       timeFrame,
        UUID          equityId,
        Integer       version,
        UUID          equitiesid
    ) {
        this.id = id;
        this.open = open;
        this.high = high;
        this.low = low;
        this.close = close;
        this.time = time;
        this.timeFrame = timeFrame;
        this.equityId = equityId;
        this.version = version;
        this.equitiesid = equitiesid;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public BigDecimal getOpen() {
        return this.open;
    }

    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    public BigDecimal getHigh() {
        return this.high;
    }

    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    public BigDecimal getLow() {
        return this.low;
    }

    public void setLow(BigDecimal low) {
        this.low = low;
    }

    public BigDecimal getClose() {
        return this.close;
    }

    public void setClose(BigDecimal close) {
        this.close = close;
    }

    public LocalDateTime getTime() {
        return this.time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public Integer getTimeFrame() {
        return this.timeFrame;
    }

    public void setTimeFrame(Integer timeFrame) {
        this.timeFrame = timeFrame;
    }

    public UUID getEquityId() {
        return this.equityId;
    }

    public void setEquityId(UUID equityId) {
        this.equityId = equityId;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public UUID getEquitiesid() {
        return this.equitiesid;
    }

    public void setEquitiesid(UUID equitiesid) {
        this.equitiesid = equitiesid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Quotes (");

        sb.append(id);
        sb.append(", ").append(open);
        sb.append(", ").append(high);
        sb.append(", ").append(low);
        sb.append(", ").append(close);
        sb.append(", ").append(time);
        sb.append(", ").append(timeFrame);
        sb.append(", ").append(equityId);
        sb.append(", ").append(version);
        sb.append(", ").append(equitiesid);

        sb.append(")");
        return sb.toString();
    }
}
