/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stocks implements Serializable {

    private static final long serialVersionUID = -1978827018;

    private UUID    id;
    private String  code;
    private String  name;
    private Integer version;

    public Stocks() {}

    public Stocks(Stocks value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.version = value.version;
    }

    public Stocks(
        UUID    id,
        String  code,
        String  name,
        Integer version
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.version = version;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Stocks (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
