/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import tech.ineb.lib.common.entities.quotes.data.tables.Currencies;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrenciesRecord extends UpdatableRecordImpl<CurrenciesRecord> implements Record5<UUID, String, String, Long, Integer> {

    private static final long serialVersionUID = -803364543;

    /**
     * Setter for <code>history.currencies.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>history.currencies.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>history.currencies.code</code>. alphabetic code
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>history.currencies.code</code>. alphabetic code
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>history.currencies.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>history.currencies.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>history.currencies.numeric_code</code>.
     */
    public void setNumericCode(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>history.currencies.numeric_code</code>.
     */
    public Long getNumericCode() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>history.currencies.version</code>.
     */
    public void setVersion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>history.currencies.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, String, Long, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, String, Long, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Currencies.CURRENCIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Currencies.CURRENCIES.CODE;
    }

    @Override
    public Field<String> field3() {
        return Currencies.CURRENCIES.NAME;
    }

    @Override
    public Field<Long> field4() {
        return Currencies.CURRENCIES.NUMERIC_CODE;
    }

    @Override
    public Field<Integer> field5() {
        return Currencies.CURRENCIES.VERSION;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Long component4() {
        return getNumericCode();
    }

    @Override
    public Integer component5() {
        return getVersion();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Long value4() {
        return getNumericCode();
    }

    @Override
    public Integer value5() {
        return getVersion();
    }

    @Override
    public CurrenciesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public CurrenciesRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public CurrenciesRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CurrenciesRecord value4(Long value) {
        setNumericCode(value);
        return this;
    }

    @Override
    public CurrenciesRecord value5(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public CurrenciesRecord values(UUID value1, String value2, String value3, Long value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CurrenciesRecord
     */
    public CurrenciesRecord() {
        super(Currencies.CURRENCIES);
    }

    /**
     * Create a detached, initialised CurrenciesRecord
     */
    public CurrenciesRecord(UUID id, String code, String name, Long numericCode, Integer version) {
        super(Currencies.CURRENCIES);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, numericCode);
        set(4, version);
    }
}
