---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    tier: "oci-pv"
  namespace: default
spec:
  storageClassName: oci-bv
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
