apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: prod-front
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
    - host: www.ineb.ru
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: prod-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: nginx:1.21.4
          imagePullPolicy: IfNotPresent
          name: frontend
          resources:
            requests:
              cpu: "0.25"
              memory: "256M"
            limits:
              cpu: "0.5"
              memory: "1G"
          ports:
            - containerPort: 8080