/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.daos;


import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import tech.ineb.lib.common.entities.quotes.data.tables.Equities;
import tech.ineb.lib.common.entities.quotes.data.tables.records.EquitiesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquitiesDao extends DAOImpl<EquitiesRecord, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities, UUID> {

    /**
     * Create a new EquitiesDao without any configuration
     */
    public EquitiesDao() {
        super(Equities.EQUITIES, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities.class);
    }

    /**
     * Create a new EquitiesDao with an attached configuration
     */
    public EquitiesDao(Configuration configuration) {
        super(Equities.EQUITIES, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities.class, configuration);
    }

    @Override
    public UUID getId(tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Equities.EQUITIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchById(UUID... values) {
        return fetch(Equities.EQUITIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities fetchOneById(UUID value) {
        return fetchOne(Equities.EQUITIES.ID, value);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Equities.EQUITIES.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByCode(String... values) {
        return fetch(Equities.EQUITIES.CODE, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Equities.EQUITIES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByName(String... values) {
        return fetch(Equities.EQUITIES.NAME, values);
    }

    /**
     * Fetch records that have <code>commission BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfCommission(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Equities.EQUITIES.COMMISSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>commission IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByCommission(BigDecimal... values) {
        return fetch(Equities.EQUITIES.COMMISSION, values);
    }

    /**
     * Fetch records that have <code>step BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfStep(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Equities.EQUITIES.STEP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>step IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByStep(BigDecimal... values) {
        return fetch(Equities.EQUITIES.STEP, values);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfActive(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Equities.EQUITIES.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByActive(BigDecimal... values) {
        return fetch(Equities.EQUITIES.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Equities.EQUITIES.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByVersion(Integer... values) {
        return fetch(Equities.EQUITIES.VERSION, values);
    }

    /**
     * Fetch records that have <code>currency_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfCurrencyId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Equities.EQUITIES.CURRENCY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>currency_id IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByCurrencyId(UUID... values) {
        return fetch(Equities.EQUITIES.CURRENCY_ID, values);
    }

    /**
     * Fetch records that have <code>country_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfCountryId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Equities.EQUITIES.COUNTRY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>country_id IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByCountryId(UUID... values) {
        return fetch(Equities.EQUITIES.COUNTRY_ID, values);
    }

    /**
     * Fetch records that have <code>stock_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchRangeOfStockId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Equities.EQUITIES.STOCK_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>stock_id IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Equities> fetchByStockId(UUID... values) {
        return fetch(Equities.EQUITIES.STOCK_ID, values);
    }
}
