/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.daos;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import tech.ineb.lib.common.entities.quotes.data.tables.Orders;
import tech.ineb.lib.common.entities.quotes.data.tables.records.OrdersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersDao extends DAOImpl<OrdersRecord, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders, UUID> {

    /**
     * Create a new OrdersDao without any configuration
     */
    public OrdersDao() {
        super(Orders.ORDERS, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders.class);
    }

    /**
     * Create a new OrdersDao with an attached configuration
     */
    public OrdersDao(Configuration configuration) {
        super(Orders.ORDERS, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders.class, configuration);
    }

    @Override
    public UUID getId(tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Orders.ORDERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchById(UUID... values) {
        return fetch(Orders.ORDERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders fetchOneById(UUID value) {
        return fetchOne(Orders.ORDERS.ID, value);
    }

    /**
     * Fetch records that have <code>volume BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfVolume(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Orders.ORDERS.VOLUME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>volume IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByVolume(BigDecimal... values) {
        return fetch(Orders.ORDERS.VOLUME, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Orders.ORDERS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByPrice(BigDecimal... values) {
        return fetch(Orders.ORDERS.PRICE, values);
    }

    /**
     * Fetch records that have <code>amount BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Orders.ORDERS.AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByAmount(BigDecimal... values) {
        return fetch(Orders.ORDERS.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>order_type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfOrderType(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Orders.ORDERS.ORDER_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>order_type IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByOrderType(Integer... values) {
        return fetch(Orders.ORDERS.ORDER_TYPE, values);
    }

    /**
     * Fetch records that have <code>order_status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfOrderStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Orders.ORDERS.ORDER_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>order_status IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByOrderStatus(Integer... values) {
        return fetch(Orders.ORDERS.ORDER_STATUS, values);
    }

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfCreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Orders.ORDERS.CREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByCreated(LocalDateTime... values) {
        return fetch(Orders.ORDERS.CREATED, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Orders.ORDERS.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByVersion(Integer... values) {
        return fetch(Orders.ORDERS.VERSION, values);
    }

    /**
     * Fetch records that have <code>equity_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchRangeOfEquityId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Orders.ORDERS.EQUITY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>equity_id IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Orders> fetchByEquityId(UUID... values) {
        return fetch(Orders.ORDERS.EQUITY_ID, values);
    }
}
