/*
 * This file is generated by jOOQ.
 */
package tech.ineb.lib.common.entities.quotes.data.tables.daos;


import java.util.List;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import tech.ineb.lib.common.entities.quotes.data.tables.Stocks;
import tech.ineb.lib.common.entities.quotes.data.tables.records.StocksRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StocksDao extends DAOImpl<StocksRecord, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks, UUID> {

    /**
     * Create a new StocksDao without any configuration
     */
    public StocksDao() {
        super(Stocks.STOCKS, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks.class);
    }

    /**
     * Create a new StocksDao with an attached configuration
     */
    public StocksDao(Configuration configuration) {
        super(Stocks.STOCKS, tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks.class, configuration);
    }

    @Override
    public UUID getId(tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Stocks.STOCKS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchById(UUID... values) {
        return fetch(Stocks.STOCKS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks fetchOneById(UUID value) {
        return fetchOne(Stocks.STOCKS.ID, value);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Stocks.STOCKS.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchByCode(String... values) {
        return fetch(Stocks.STOCKS.CODE, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Stocks.STOCKS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchByName(String... values) {
        return fetch(Stocks.STOCKS.NAME, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Stocks.STOCKS.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<tech.ineb.lib.common.entities.quotes.data.tables.pojos.Stocks> fetchByVersion(Integer... values) {
        return fetch(Stocks.STOCKS.VERSION, values);
    }
}
